import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "sony-wh-1000xm5",
    category: "digital",
    brand: "Sony",
    model: "WH-1000XM5",
    productName: { zh: "索尼降噪耳机", en: "Sony Noise Cancelling Headphones", ja: "ソニー ノイズキャンセリングヘッドホン" },
    tier: "hang",
    score: 96,
    valueScore: 88,
    qualityScore: 97,
    audience: { zh: "通勤、办公室、长途飞行党", en: "Commuters, office workers, frequent flyers", ja: "通勤、オフィス、長距離移動が多い人" },
    summary: { zh: "降噪、佩戴、声音和稳定性都很均衡，是不想折腾用户的闭眼买。", en: "Balanced ANC, comfort, sound, and stability. An easy default pick.", ja: "ANC、装着感、音質、安定性のバランスが強い定番。" },
    why: { zh: "综合体验长期稳定，缺点不致命，替代品很难在所有维度一起赢它。", en: "It stays consistently excellent across the full ownership experience.", ja: "総合体験が安定しており、全項目で勝つ代替品が少ない。" },
    quickVerdict: { zh: "预算够就上，省掉大部分选择成本。", en: "Buy it if the budget fits.", ja: "予算が合うならかなり堅い選択。" },
    pros: [{ zh: "降噪强", en: "Excellent ANC", ja: "ANCが強い" }, { zh: "佩戴轻", en: "Light comfort", ja: "軽くて快適" }, { zh: "App 生态成熟", en: "Mature app ecosystem", ja: "アプリが成熟" }],
    cons: [{ zh: "不可折叠", en: "Does not fold", ja: "折りたためない" }, { zh: "价格偏高", en: "Premium price", ja: "価格は高め" }],
    tags: [{ zh: "闭眼买", en: "Default pick", ja: "迷ったらこれ" }, { zh: "通勤神器", en: "Commute hero", ja: "通勤向け" }]
  },
  {
    id: "anker-737-powerbank",
    category: "digital",
    brand: "Anker",
    model: "737",
    productName: { zh: "Anker 737 充电宝", en: "Anker 737 Power Bank", ja: "Anker 737 モバイルバッテリー" },
    tier: "top",
    score: 90,
    valueScore: 84,
    qualityScore: 93,
    audience: { zh: "重度手机、平板、轻薄本用户", en: "Heavy phone, tablet, and laptop users", ja: "スマホ・タブレット・薄型PCのヘビーユーザー" },
    summary: { zh: "功率、容量和屏显都很扎实，适合真正需要大功率移动供电的人。", en: "Strong wattage, capacity, and display for real mobile power needs.", ja: "高出力・容量・表示がしっかりした実用派。" },
    why: { zh: "不是最轻，但稳定性和信息透明度很强。", en: "Not the lightest, but reliable and transparent.", ja: "軽くはないが信頼性と情報表示が強い。" },
    quickVerdict: { zh: "不是人人需要，但需要的人会很爱。", en: "Not for everyone, but loved by its target users.", ja: "万人向けではないが刺さる人には刺さる。" },
    pros: [{ zh: "输出强", en: "High output", ja: "高出力" }, { zh: "屏显清楚", en: "Useful display", ja: "表示が便利" }],
    cons: [{ zh: "偏重", en: "Heavy", ja: "重い" }, { zh: "日常通勤有点过剩", en: "Overkill for casual use", ja: "日常用途には過剰" }],
    tags: [{ zh: "适合新手", en: "Beginner friendly", ja: "初心者向け" }, { zh: "商务出差", en: "Travel ready", ja: "出張向け" }]
  },
  {
    id: "cerave-cleanser",
    category: "beauty",
    brand: "CeraVe",
    model: "Hydrating Cleanser",
    productName: { zh: "适乐肤保湿洁面", en: "CeraVe Hydrating Cleanser", ja: "CeraVe 保湿クレンザー" },
    tier: "hang",
    score: 94,
    valueScore: 95,
    qualityScore: 90,
    audience: { zh: "干皮、敏感肌、屏障不稳用户", en: "Dry, sensitive, barrier-damaged skin", ja: "乾燥肌、敏感肌、バリアが弱い人" },
    summary: { zh: "温和、便宜、大容量，基础洁面里很难翻车。", en: "Gentle, affordable, large format. Hard to mess up.", ja: "低刺激・安価・大容量で失敗しにくい。" },
    why: { zh: "它不靠故事感取胜，而是靠稳定和低刺激长期留在高位。", en: "It wins through reliability, not hype.", ja: "派手さより安定性で評価される。" },
    quickVerdict: { zh: "护肤预算先投这里，不丢人。", en: "A sensible place to spend skincare budget.", ja: "基礎ケアとしてかなり妥当。" },
    pros: [{ zh: "温和不拔干", en: "Gentle and non-stripping", ja: "つっぱりにくい" }, { zh: "性价比高", en: "Great value", ja: "コスパ良い" }],
    cons: [{ zh: "清洁力不适合浓妆", en: "Not for heavy makeup", ja: "濃いメイクには弱い" }],
    tags: [{ zh: "性价比高", en: "Great value", ja: "高コスパ" }, { zh: "屏障友好", en: "Barrier friendly", ja: "バリアに優しい" }]
  },
  {
    id: "viral-gold-serum",
    category: "beauty",
    brand: "GlowTalk",
    model: "Gold Peptide Serum",
    productName: { zh: "金箔胜肽精华", en: "Gold Peptide Serum", ja: "ゴールドペプチド美容液" },
    tier: "npc",
    score: 54,
    valueScore: 42,
    qualityScore: 62,
    audience: { zh: "喜欢仪式感但不追求硬核功效的人", en: "People who enjoy ritual more than hard results", ja: "効果より気分を重視する人" },
    summary: { zh: "包装和话术很会，但核心成分和肤感没有明显越级。", en: "Good packaging and story, average formula impact.", ja: "見せ方は上手いが処方の強さは普通。" },
    why: { zh: "热度大于实力，同价位有更稳的功效型选择。", en: "The hype outruns the performance.", ja: "話題性が実力を上回る。" },
    quickVerdict: { zh: "想买快乐可以，想买功效先冷静。", en: "Fine for fun, weak as a performance buy.", ja: "気分買いならあり、効果目的なら慎重に。" },
    pros: [{ zh: "包装好看", en: "Pretty packaging", ja: "パッケージが良い" }],
    cons: [{ zh: "营销大于实力", en: "Marketing over performance", ja: "宣伝先行" }, { zh: "价格虚高", en: "Overpriced", ja: "割高" }],
    tags: [{ zh: "营销大于实力", en: "More hype than power", ja: "宣伝先行" }]
  },
  {
    id: "calbee-fruit-granola",
    category: "food",
    brand: "Calbee",
    model: "Fruit Granola",
    productName: { zh: "卡乐比水果麦片", en: "Calbee Fruit Granola", ja: "カルビー フルグラ" },
    tier: "elite",
    score: 82,
    valueScore: 79,
    qualityScore: 83,
    audience: { zh: "早餐懒人、酸奶搭配党", en: "Lazy breakfast and yogurt bowl people", ja: "朝食を手軽に済ませたい人" },
    summary: { zh: "好吃、方便、稳定，但糖分和热量别装看不见。", en: "Tasty and easy, but sugar and calories are real.", ja: "おいしく便利だが糖分とカロリーには注意。" },
    why: { zh: "体验优秀但健康光环有限，适合作为方便食品而不是减脂神物。", en: "Excellent convenience food, not a health miracle.", ja: "便利食品として優秀、健康食品としては過信禁物。" },
    quickVerdict: { zh: "囤可以，别把它当健身餐。", en: "Stock it, but don't treat it as fitness food.", ja: "常備はあり、健康食扱いは注意。" },
    pros: [{ zh: "口味稳定", en: "Consistent taste", ja: "味が安定" }, { zh: "搭配方便", en: "Easy to pair", ja: "合わせやすい" }],
    cons: [{ zh: "糖分不低", en: "Not low sugar", ja: "糖分は低くない" }],
    tags: [{ zh: "懒人早餐", en: "Lazy breakfast", ja: "時短朝食" }]
  },
  {
    id: "mystery-protein-cookie",
    category: "food",
    brand: "FitBite",
    model: "Protein Cookie",
    productName: { zh: "高蛋白代餐曲奇", en: "Protein Meal Cookie", ja: "プロテイン置き換えクッキー" },
    tier: "trash",
    score: 31,
    valueScore: 28,
    qualityScore: 35,
    audience: { zh: "不建议作为长期代餐", en: "Not recommended as a regular meal replacement", ja: "日常の置き換えには非推奨" },
    summary: { zh: "配料表和口感都很尴尬，代餐感强但满足感弱。", en: "Awkward ingredients and texture, weak satisfaction.", ja: "原材料と食感が微妙で満足感が弱い。" },
    why: { zh: "把普通零食包装成健康答案，实际性价比和体验都拉胯。", en: "A snack dressed as a health solution.", ja: "普通のお菓子を健康商品っぽく見せている。" },
    quickVerdict: { zh: "别买，真饿就吃顿正常饭。", en: "Skip it. Eat a real meal.", ja: "買わずに普通の食事を。" },
    pros: [{ zh: "便携", en: "Portable", ja: "持ち運びやすい" }],
    cons: [{ zh: "工业垃圾", en: "Ultra-processed mess", ja: "加工感が強い" }, { zh: "不顶饱", en: "Not filling", ja: "腹持ちが弱い" }],
    tags: [{ zh: "工业垃圾", en: "Industrial snack", ja: "加工感強め" }]
  },
  {
    id: "pidan-cat-litter",
    category: "pet",
    brand: "Pidan",
    model: "Tofu Cat Litter",
    productName: { zh: "彼诞豆腐猫砂", en: "Pidan Tofu Cat Litter", ja: "Pidan 豆腐猫砂" },
    tier: "top",
    score: 88,
    valueScore: 86,
    qualityScore: 87,
    audience: { zh: "城市养猫家庭、对粉尘敏感的人", en: "Urban cat homes and dust-sensitive owners", ja: "都市部の猫家庭、粉じんが気になる人" },
    summary: { zh: "结团、除臭和清理体验都在线，是猫砂里的稳妥选择。", en: "Reliable clumping, odor control, and cleanup.", ja: "固まり・消臭・掃除のバランスが良い。" },
    why: { zh: "没有神化必要，但确实比很多低价猫砂省心。", en: "Not magic, just easier than many cheap options.", ja: "魔法ではないが安物より楽。" },
    quickVerdict: { zh: "猫接受的话，可以长期回购。", en: "If your cat accepts it, it is repeat-buy worthy.", ja: "猫が受け入れるならリピート候補。" },
    pros: [{ zh: "粉尘较低", en: "Lower dust", ja: "粉じん少なめ" }, { zh: "结团快", en: "Quick clumping", ja: "固まりやすい" }],
    cons: [{ zh: "不同猫接受度不同", en: "Cat preference varies", ja: "猫によって好みが分かれる" }],
    tags: [{ zh: "适合新手", en: "Beginner friendly", ja: "初心者向け" }]
  },
  {
    id: "roborock-q-revo",
    category: "pet",
    brand: "Roborock",
    model: "Q Revo",
    productName: { zh: "石头扫拖机器人", en: "Roborock Robot Vacuum", ja: "Roborock ロボット掃除機" },
    tier: "hang",
    score: 93,
    valueScore: 91,
    qualityScore: 92,
    audience: { zh: "有宠家庭、毛发焦虑、懒人清洁党", en: "Pet homes, hair anxiety, low-effort cleaning", ja: "ペット家庭、抜け毛対策、掃除を楽にしたい人" },
    summary: { zh: "自动化程度高，宠物毛发和日常灰尘处理很省心。", en: "High automation that makes pet hair and daily dust easier.", ja: "自動化が高くペット毛と日常清掃が楽。" },
    why: { zh: "把清洁频率从意志力问题变成机器日程，价值感很直接。", en: "It turns cleaning discipline into a schedule.", ja: "掃除の意思力をスケジュール化できる。" },
    quickVerdict: { zh: "有宠物且预算够，幸福感提升明显。", en: "For pet homes with budget, the upgrade is obvious.", ja: "ペット家庭なら満足度が高い。" },
    pros: [{ zh: "自动洗拖布", en: "Auto mop washing", ja: "モップ自動洗浄" }, { zh: "毛发处理强", en: "Good with pet hair", ja: "ペット毛に強い" }],
    cons: [{ zh: "需要预留基站空间", en: "Needs dock space", ja: "ドックの場所が必要" }],
    tags: [{ zh: "闭眼买", en: "Default pick", ja: "迷ったらこれ" }, { zh: "养宠救星", en: "Pet-home saver", ja: "ペット家庭向け" }]
  },
  {
    id: "decathlon-hiking-pack",
    category: "sports",
    brand: "Decathlon",
    model: "MH500 30L",
    productName: { zh: "迪卡侬徒步背包", en: "Decathlon Hiking Backpack", ja: "デカトロン ハイキングバックパック" },
    tier: "elite",
    score: 80,
    valueScore: 89,
    qualityScore: 76,
    audience: { zh: "周末徒步、短线露营、新手户外", en: "Weekend hikers, short camping trips, beginners", ja: "週末ハイク、短期キャンプ、初心者" },
    summary: { zh: "价格友好、功能够用，适合还没准备烧钱的新户外玩家。", en: "Affordable and capable for new outdoor users.", ja: "安くて必要十分、初心者に向く。" },
    why: { zh: "它不是装备发烧友答案，但很符合入门真实需求。", en: "Not enthusiast-grade, but aligned with beginner needs.", ja: "上級者向けではないが入門には現実的。" },
    quickVerdict: { zh: "先买它去走两次，再决定要不要升级。", en: "Use it first, upgrade later if needed.", ja: "まず使ってからアップグレード判断で良い。" },
    pros: [{ zh: "性价比高", en: "Great value", ja: "高コスパ" }, { zh: "分仓实用", en: "Useful compartments", ja: "収納が実用的" }],
    cons: [{ zh: "质感不算顶级", en: "Not premium", ja: "高級感は普通" }],
    tags: [{ zh: "性价比高", en: "Great value", ja: "高コスパ" }, { zh: "适合新手", en: "Beginner friendly", ja: "初心者向け" }]
  },
  {
    id: "hoka-bondi-8",
    category: "sports",
    brand: "Hoka",
    model: "Bondi 8",
    productName: { zh: "Hoka Bondi 8 跑鞋", en: "Hoka Bondi 8 Running Shoes", ja: "Hoka Bondi 8 ランニングシューズ" },
    tier: "top",
    score: 89,
    valueScore: 76,
    qualityScore: 92,
    audience: { zh: "大体重、慢跑、久站通勤用户", en: "Heavier runners, slow runs, long standing days", ja: "体重重め、ゆっくりラン、長時間立つ人" },
    summary: { zh: "缓震厚实，脚感友好，但不是速度训练鞋。", en: "Plush cushioning, friendly feel, not for speed work.", ja: "クッションが厚く快適、スピード練習向きではない。" },
    why: { zh: "定位清晰且兑现度高，买之前只需要确认你要的是缓震。", en: "Clear positioning with strong execution.", ja: "役割が明確で完成度が高い。" },
    quickVerdict: { zh: "想要软弹保护感，可以冲。", en: "Go for it if protection and cushioning matter.", ja: "保護感とクッション重視ならあり。" },
    pros: [{ zh: "缓震强", en: "Strong cushioning", ja: "クッション強い" }, { zh: "久站舒服", en: "Comfortable for standing", ja: "立ち仕事に楽" }],
    cons: [{ zh: "不够灵活", en: "Not very agile", ja: "機敏さは弱い" }, { zh: "价格高", en: "Expensive", ja: "高め" }],
    tags: [{ zh: "大体重友好", en: "Heavy-runner friendly", ja: "体重重め向け" }]
  }
];

export function getProduct(id: string) {
  return products.find((product) => product.id === id);
}
