import type { RankingMockItem } from "@/types/product";

export const gpu5060TiRanking: RankingMockItem[] = [
  {
    id: "gpu-5060ti-001",
    brand: "Colorful",
    model: "RTX 5060 Ti Battle AX DUO 8GB-V",
    productName: "七彩虹 RTX 5060 Ti 战斧 DUO",
    tier: "夯",
    rank: 1,
    summary: "这一代真正的甜品守门员，价格压得狠。",
    pros: ["性价比极高", "小机箱友好", "散热够用"],
    cons: ["双风扇颜值一般", "RGB较弱"],
    tags: ["甜品卡", "性价比", "装机热门"],
    score: 96,
    valueScore: 99,
    qualityScore: 86,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "gpu-5060ti-002",
    brand: "GALAX",
    model: "RTX 5060 Ti 魔刃 MAX OC",
    productName: "影驰 RTX 5060 Ti 魔刃",
    tier: "夯",
    rank: 2,
    summary: "散热和做工明显超这个价位。",
    pros: ["三风扇散热强", "静音表现好", "装机圈口碑高"],
    cons: ["部分地区溢价", "灯效普通"],
    tags: ["三风扇", "热门", "B站推荐"],
    score: 94,
    valueScore: 92,
    qualityScore: 92,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "gpu-5060ti-003",
    brand: "MAXSUN",
    model: "RTX 5060 Ti iCraft OC16G",
    productName: "铭瑄 RTX 5060 Ti iCraft",
    tier: "夯",
    rank: 3,
    summary: "白卡党这一代真的可以闭眼冲。",
    pros: ["白色颜值高", "海景房适配度高", "散热进步明显"],
    cons: ["保值率一般", "品牌争议还在"],
    tags: ["白卡", "海景房", "小红书热门"],
    score: 91,
    valueScore: 90,
    qualityScore: 85,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "gpu-5060ti-004",
    brand: "Colorful",
    model: "RTX 5060 Ti 战斧 豪华版 16GB",
    productName: "七彩虹 RTX 5060 Ti 战斧豪华",
    tier: "顶级",
    rank: 4,
    summary: "散热更强，但价格已经开始没那么香。",
    pros: ["三风扇散热", "供电更稳", "颜值不错"],
    cons: ["价格上涨明显"],
    tags: ["RGB", "高配战斧"],
    score: 90,
    valueScore: 84,
    qualityScore: 92,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "gpu-5060ti-005",
    brand: "MSI",
    model: "RTX 5060 Ti GAMING TRIO OC",
    productName: "微星 RTX 5060 Ti GAMING TRIO",
    tier: "顶级",
    rank: 5,
    summary: "传统高端非公味儿很正，但价格也真高。",
    pros: ["静音优秀", "做工扎实", "供电稳定"],
    cons: ["溢价高", "性价比偏低"],
    tags: ["高端非公", "静音", "传统大厂"],
    score: 89,
    valueScore: 72,
    qualityScore: 95,
    sentiment: "mixed",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-006",
    brand: "ASUS",
    model: "RTX 5060 Ti TUF Gaming OC",
    productName: "华硕 RTX 5060 Ti TUF",
    tier: "顶级",
    rank: 6,
    summary: "很稳，但华硕税还是太明显。",
    pros: ["散热优秀", "做工稳定", "品牌认可度高"],
    cons: ["价格偏贵", "没啥惊喜"],
    tags: ["TUF", "稳定", "华硕税"],
    score: 88,
    valueScore: 70,
    qualityScore: 94,
    sentiment: "mixed",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-007",
    brand: "Colorful",
    model: "iGame RTX 5060 Ti Ultra W OC 16GB-V",
    productName: "七彩虹 RTX 5060 Ti Ultra W",
    tier: "人上人",
    rank: 7,
    summary: "二次元海景房浓度超标。",
    pros: ["外观吸睛", "白色主题好搭", "RGB效果强"],
    cons: ["溢价明显", "不走性价比路线"],
    tags: ["二次元", "白卡", "潮流"],
    score: 86,
    valueScore: 68,
    qualityScore: 87,
    sentiment: "mixed",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-008",
    brand: "GALAX",
    model: "RTX 5060 Ti 星曜 OC",
    productName: "影驰 RTX 5060 Ti 星曜",
    tier: "人上人",
    rank: 8,
    summary: "白色 RGB 玩家最爱。",
    pros: ["灯效氛围感强", "海景房神器", "颜值高"],
    cons: ["容易缺货", "价格偏高"],
    tags: ["RGB", "白色", "海景房"],
    score: 85,
    valueScore: 69,
    qualityScore: 88,
    sentiment: "positive",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-009",
    brand: "Yeston",
    model: "RTX 5060 Ti Sakura Atlantis",
    productName: "盈通 RTX 5060 Ti 樱瞳",
    tier: "人上人",
    rank: 9,
    summary: "女生装机和二次元用户直接疯狂。",
    pros: ["颜值极强", "白色海景房绝配"],
    cons: ["溢价严重", "不算纯性价比"],
    tags: ["樱瞳", "二次元", "颜值党"],
    score: 84,
    valueScore: 65,
    qualityScore: 85,
    sentiment: "mixed",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-010",
    brand: "ZOTAC",
    model: "RTX 5060 Ti XGAMING OC",
    productName: "索泰 RTX 5060 Ti XGAMING",
    tier: "npc",
    rank: 10,
    summary: "没啥槽点，也没啥记忆点。",
    pros: ["稳定", "温度正常"],
    cons: ["讨论度低", "外观一般"],
    tags: ["稳定", "普通"],
    score: 78,
    valueScore: 76,
    qualityScore: 76,
    sentiment: "neutral",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-011",
    brand: "GIGABYTE",
    model: "RTX 5060 Ti EAGLE OC",
    productName: "技嘉 RTX 5060 Ti EAGLE",
    tier: "npc",
    rank: 11,
    summary: "外观看着猛，但实际没太多亮点。",
    pros: ["散热正常", "品牌认知度高"],
    cons: ["噪音一般", "供电普通"],
    tags: ["普通", "争议"],
    score: 74,
    valueScore: 72,
    qualityScore: 70,
    sentiment: "neutral",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-012",
    brand: "PNY",
    model: "RTX 5060 Ti EPIC-X RGB OC",
    productName: "PNY RTX 5060 Ti EPIC-X",
    tier: "npc",
    rank: 12,
    summary: "海外味很浓，但国内存在感偏低。",
    pros: ["偶尔价格便宜", "稳定性还行"],
    cons: ["售后认知低", "讨论热度低"],
    tags: ["海外品牌", "低调"],
    score: 73,
    valueScore: 75,
    qualityScore: 71,
    sentiment: "neutral",
    recommendationLevel: "consider"
  },
  {
    id: "gpu-5060ti-013",
    brand: "GIGABYTE",
    model: "RTX 5060 Ti WINDFORCE OC",
    productName: "技嘉 RTX 5060 Ti WINDFORCE",
    tier: "拉完了",
    rank: 13,
    summary: "价格没便宜多少，但体验提升有限。",
    pros: ["偶尔有低价"],
    cons: ["散热一般", "噪音偏明显", "互联网评价两极化"],
    tags: ["争议", "避雷"],
    score: 66,
    valueScore: 67,
    qualityScore: 60,
    sentiment: "negative",
    recommendationLevel: "avoid"
  },
  {
    id: "gpu-5060ti-014",
    brand: "ONDA",
    model: "RTX 5060 Ti 神盾",
    productName: "昂达 RTX 5060 Ti 神盾",
    tier: "拉完了",
    rank: 14,
    summary: "便宜是真便宜，但很多人不太敢碰。",
    pros: ["价格低"],
    cons: ["品牌信任度低", "做工一般", "二手保值差"],
    tags: ["低价", "避雷"],
    score: 58,
    valueScore: 65,
    qualityScore: 50,
    sentiment: "negative",
    recommendationLevel: "avoid"
  }
];

export const rtx5060TiGpuRanking = gpu5060TiRanking;

export const mechanicalKeyboardRanking: RankingMockItem[] = [
  {
    id: "keyboard-001",
    brand: "AULA",
    model: "F87 Pro",
    productName: "狼蛛 F87 Pro",
    tier: "夯",
    rank: 1,
    summary: "这一代真正的百元卷王。",
    pros: ["性价比极高", "手感超预期", "三模齐全", "小红书热度爆炸"],
    cons: ["品牌调性一般", "默认键帽普通"],
    tags: ["卷王", "三模", "键圈热门"],
    score: 96,
    valueScore: 99,
    qualityScore: 84,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "keyboard-002",
    brand: "MCHOSE",
    model: "G75 Pro",
    productName: "迈从 G75 Pro",
    tier: "夯",
    rank: 2,
    summary: "最近小红书键圈出镜率高得离谱。",
    pros: ["颜值高", "轴体优秀", "性价比强"],
    cons: ["配列需要适应"],
    tags: ["客制化", "小红书热门", "75配列"],
    score: 94,
    valueScore: 95,
    qualityScore: 88,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "keyboard-003",
    brand: "IQUNIX",
    model: "EV63",
    productName: "IQUNIX EV63",
    tier: "顶级",
    rank: 3,
    summary: "高级感和做工确实不是普通键盘能碰的。",
    pros: ["做工顶级", "铝坨坨质感强", "设计感优秀"],
    cons: ["价格高", "小配列门槛高"],
    tags: ["铝坨坨", "高端", "设计感"],
    score: 91,
    valueScore: 72,
    qualityScore: 96,
    sentiment: "positive",
    recommendationLevel: "consider"
  },
  {
    id: "keyboard-004",
    brand: "WOBKEY",
    model: "Rainy75",
    productName: "Rainy75",
    tier: "顶级",
    rank: 4,
    summary: "雨75几乎成了客制化入坑标准答案。",
    pros: ["声音优秀", "Gasket体验好", "键圈认可度高"],
    cons: ["价格不低", "容易缺货"],
    tags: ["客制化", "雨75", "Gasket"],
    score: 90,
    valueScore: 83,
    qualityScore: 92,
    sentiment: "positive",
    recommendationLevel: "recommend"
  },
  {
    id: "keyboard-005",
    brand: "Razer",
    model: "BlackWidow V4 Pro",
    productName: "雷蛇 黑寡妇 V4 Pro",
    tier: "人上人",
    rank: 5,
    summary: "电竞房氛围感直接拉满。",
    pros: ["RGB氛围强", "品牌信仰", "电竞感强"],
    cons: ["溢价高", "性价比一般"],
    tags: ["RGB", "电竞", "信仰"],
    score: 87,
    valueScore: 66,
    qualityScore: 91,
    sentiment: "mixed",
    recommendationLevel: "consider"
  },
  {
    id: "keyboard-006",
    brand: "Lofree",
    model: "Flow84",
    productName: "洛斐 Flow84",
    tier: "人上人",
    rank: 6,
    summary: "女生办公桌浓度超标。",
    pros: ["颜值高", "超薄设计", "办公体验舒服"],
    cons: ["游戏党不一定喜欢", "价格偏高"],
    tags: ["女生桌搭", "颜值", "超薄"],
    score: 85,
    valueScore: 70,
    qualityScore: 88,
    sentiment: "positive",
    recommendationLevel: "consider"
  },
  {
    id: "keyboard-007",
    brand: "Dareu",
    model: "A98",
    productName: "达尔优 A98",
    tier: "npc",
    rank: 7,
    summary: "很稳，但现在已经不算特别卷了。",
    pros: ["稳定", "配列舒服"],
    cons: ["讨论热度下降", "卷不过新品牌"],
    tags: ["98配列", "老牌"],
    score: 78,
    valueScore: 75,
    qualityScore: 80,
    sentiment: "neutral",
    recommendationLevel: "consider"
  },
  {
    id: "keyboard-008",
    brand: "Corsair",
    model: "K70 RGB Pro",
    productName: "海盗船 K70 RGB Pro",
    tier: "npc",
    rank: 8,
    summary: "传统电竞味很重，但已经不够新了。",
    pros: ["品牌经典", "灯效强"],
    cons: ["偏传统", "声音一般", "价格偏高"],
    tags: ["传统电竞", "RGB"],
    score: 74,
    valueScore: 68,
    qualityScore: 82,
    sentiment: "neutral",
    recommendationLevel: "consider"
  },
  {
    id: "keyboard-009",
    brand: "Cherry",
    model: "G80-3000",
    productName: "Cherry G80-3000",
    tier: "拉完了",
    rank: 9,
    summary: "时代眼泪，现在年轻人真不太买账。",
    pros: ["经典", "原厂轴"],
    cons: ["声音空", "手感老派", "性价比低"],
    tags: ["时代眼泪", "老派"],
    score: 61,
    valueScore: 52,
    qualityScore: 76,
    sentiment: "negative",
    recommendationLevel: "avoid"
  },
  {
    id: "keyboard-010",
    brand: "Logitech",
    model: "G913",
    productName: "罗技 G913",
    tier: "拉完了",
    rank: 10,
    summary: "以前很帅，现在大家都觉得有点电子垃圾感了。",
    pros: ["无线稳定", "品牌强"],
    cons: ["价格虚高", "键圈口碑下降", "性价比低"],
    tags: ["电子垃圾", "争议"],
    score: 58,
    valueScore: 48,
    qualityScore: 74,
    sentiment: "negative",
    recommendationLevel: "avoid"
  }
];
